import { Html, Head, Main, NextScript } from 'next/document';

const Document = () => (
  <Html lang="ja">
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="robots" content="noindex" />
      <link rel="manifest" href="/manifest.json" />
    </Head>
    <body>
      <Main />
      <NextScript />
    </body>
  </Html>
);

export default Document;
