'use client';

import { MantineProvider } from '@mantine/core';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import clsx from 'clsx';
import { init } from 'i18next';
import { Noto_Sans_JP } from 'next/font/google';
import Script from 'next/script';
import { PropsWithChildren } from 'react';
import { z } from 'zod';
import { zodI18nMap } from 'zod-i18n-map';

import { NaNotifications } from '@/components/NaNotifications';
import type { NaNotificationsProps } from '@/components/NaNotifications';

import { useI18nStore } from '@/stores/i18n';

import zodLocalesJa from '@/utils/i18n/locales/ja/zod.json';

import { mantineCustomTheme } from '@/config';

import '@/styles/global.css';
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import '@mantine/notifications/styles.css';

const notoSansJp = Noto_Sans_JP({ subsets: ['latin'], variable: '--font-noto-sans-jp' });
const queryClient = new QueryClient();

const notificationsProps: NaNotificationsProps = {
  position: 'top-right',
  autoClose: 5000,
  containerWidth: 400,
  notificationMaxHeight: 250,
  limit: 5,
  zIndex: 1000,
};

const Layout = ({ children }: PropsWithChildren) => {
  const lng = useI18nStore((store) => store.lang);
  init({
    lng,
    resources: {
      ja: { zod: zodLocalesJa },
    },
  });
  z.setErrorMap(zodI18nMap);

  return (
    <html lang="ja" className={clsx(notoSansJp.variable, 'font-sans')}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex" />
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={clsx('select-none p-2 text-sm', notoSansJp.className)}>
        <QueryClientProvider client={queryClient}>
          <MantineProvider theme={mantineCustomTheme}>
            {children}
            <NaNotifications {...notificationsProps} />
            <ReactQueryDevtools initialIsOpen={false} />
          </MantineProvider>
        </QueryClientProvider>
      </body>
      <Script src="/main.js" defer />
    </html>
  );
};

export default Layout;
