name: Check the source code

on:
  push:
    branches:
      - "feat/**"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install node modules
        run: pnpm install

      - name: Run Prettier
        run: pnpm fmt

      - name: Run ESLint
        run: pnpm lint
